name: 'Linux Clang'

#env:
#  CMAKE_VERSION: '3.16.x'
#  CMAKE_BUILD_TYPE: 'Release'
#  CMAKE_BUILD_PREFIX: './build'

on:
  push:
  pull_request:

jobs:
  build:
    name: '🚧 Clang v${{ matrix.compiler }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [ 3.5.0, 3.5.2, 3.6.0 , 3.6.1 , 3.6.2 , 3.7.0 , 3.7.1 , 3.8.0 , 3.8.1 , 3.9.0 , 3.9.1 , 4.0.0 , 5.0.1 , 5.0.2 , 6.0.0 , 6.0.1 , 7.0.0 , 7.0.1 , 8.0.0 , 9.0.0 , 9.0.1 , 10.0.0 ,  10.0.1 , 11.0.0 , 11.0.1 , 11.1.0 , 12.0.0 , 12.0.1 , 13.0.0 ]
        c-standard: [90,99,11,17,23]
        cxx-standard: [98,11,14,17,20,23]
        include:
        - {}

    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2.4.0

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: |
          C:/Program Files/LLVM
          ./llvm
        key: llvm-${{ matrix.compiler }}-linux
        
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "${{ matrix.compiler }}"
        force-version: true
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        
    - name: '${{ matrix.icon }} Setup CMake'
      uses: jwlawson/actions-setup-cmake@v1.11
      with:
        cmake-version: '3.21.x'
        github-api-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Print compiler version
      run: clang --version
