name: 'Linux Clang'

env:
  CMAKE_VERSION: '3.21.x'
  CMAKE_BUILD_TYPE: 'Release'
  CMAKE_BUILD_PREFIX: './build'

on:
  push:
  pull_request:

jobs:
  build:
    name: '🚧 Clang v${{ matrix.compiler }} C${{ matrix.c-standard }}, C++${{ matrix.cxx-standard }}, Ex${{ matrix.extensions }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [ 3.5.0, 3.5.2, 3.6.0 , 3.6.1 , 3.6.2 , 3.7.0 , 3.7.1 , 3.8.0 , 3.9.0 , 4.0.0 , 5.0.1 , 5.0.2 , 6.0.0 , 7.0.0 , 8.0.0 , 9.0.0 , 9.0.1 , 10.0.0 ,  10.0.1 , 11.0.0 , 12.0.0 , 13.0.0 ]
        c-standard: [ 90 ]
        extensions: [ OFF ]
        cxx-standard: [98,11,14,17,20,23]
        exclude:
         # https://clang.llvm.org/cxx_status.html
         # 3.5.0
         - compiler: 3.5.0
           c-standard: 17
         - compiler: 3.5.0
           cxx-standard: 17   
         - compiler: 3.5.0
           c-standard: 20
         - compiler: 3.5.0
           cxx-standard: 20 
         - compiler: 3.5.0
           c-standard: 23
         - compiler: 3.5.0
           cxx-standard: 23
         # 3.5.2  
         - compiler: 3.5.2
           c-standard: 17
         - compiler: 3.5.2
           cxx-standard: 17   
         - compiler: 3.5.2
           c-standard: 20
         - compiler: 3.5.2
           cxx-standard: 20 
         - compiler: 3.5.2
           c-standard: 23
         - compiler: 3.5.2
           cxx-standard: 23   
         # 3.6.0
         - compiler: 3.6.0
           c-standard: 17
         - compiler: 3.6.0
           cxx-standard: 17   
         - compiler: 3.6.0
           c-standard: 20
         - compiler: 3.6.0
           cxx-standard: 20 
         - compiler: 3.6.0
           c-standard: 23
         - compiler: 3.6.0
           cxx-standard: 23   
         # 3.6.1           
         - compiler: 3.6.1 
           c-standard: 17
         - compiler: 3.6.1 
           cxx-standard: 17   
         - compiler: 3.6.1 
           c-standard: 20
         - compiler: 3.6.1 
           cxx-standard: 20 
         - compiler: 3.6.1 
           c-standard: 23
         - compiler: 3.6.1 
           cxx-standard: 23   
         # 3.6.2
         - compiler: 3.6.2
           c-standard: 17
         - compiler: 3.6.2
           cxx-standard: 17   
         - compiler: 3.6.2
           c-standard: 20
         - compiler: 3.6.2
           cxx-standard: 20 
         - compiler: 3.6.2
           c-standard: 23
         - compiler: 3.6.2
           cxx-standard: 23   
         # 3.7.0
         - compiler: 3.7.0
           c-standard: 17
         - compiler: 3.7.0
           cxx-standard: 17   
         - compiler: 3.7.0
           c-standard: 20
         - compiler: 3.7.0
           cxx-standard: 20 
         - compiler: 3.7.0
           c-standard: 23
         - compiler: 3.7.0
           cxx-standard: 23        
         # 3.7.1  
         - compiler: 3.7.1
           c-standard: 17
         - compiler: 3.7.1
           cxx-standard: 17   
         - compiler: 3.7.1
           c-standard: 20
         - compiler: 3.7.1
           cxx-standard: 20 
         - compiler: 3.7.1
           c-standard: 23
         - compiler: 3.7.1
           cxx-standard: 23   
          # 3.8.0
         - compiler: 3.8.0
           c-standard: 17
         - compiler: 3.8.0
           cxx-standard: 17   
         - compiler: 3.8.0
           c-standard: 20
         - compiler: 3.8.0
           cxx-standard: 20 
         - compiler: 3.8.0
           c-standard: 23
         - compiler: 3.8.0
           cxx-standard: 23     
          # 3.9.0
         - compiler: 3.9.0
           c-standard: 17
         - compiler: 3.9.0
           cxx-standard: 17   
         - compiler: 3.9.0
           c-standard: 20
         - compiler: 3.9.0
           cxx-standard: 20 
         - compiler: 3.9.0
           c-standard: 23
         - compiler: 3.9.0
           cxx-standard: 23   
          # 4.0.0
         - compiler: 4.0.0
           c-standard: 17
         - compiler: 4.0.0
           cxx-standard: 17   
         - compiler: 4.0.0
           c-standard: 20
         - compiler: 4.0.0
           cxx-standard: 20 
         - compiler: 4.0.0
           c-standard: 23
         - compiler: 4.0.0
           cxx-standard: 23       

    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2.4.0

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: |
          C:/Program Files/LLVM
          ./llvm
        key: llvm-${{ matrix.compiler }}-linux
        
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "${{ matrix.compiler }}"
        force-version: true
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        
    - name: '${{ matrix.icon }} Setup CMake'
      uses: jwlawson/actions-setup-cmake@v1.11
      with:
        cmake-version: ${{ env.CMAKE_VERSION }}
        github-api-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Print compiler version
      run: clang --version

    - name: '🔧 Configure'
      env:
        CC: clang
        CXX: clang++
      run: cmake -S . -B ${{ env.CMAKE_BUILD_PREFIX }} -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -DCMAKE_MINIMUM_VERSION=${{ env.CMAKE_VERSION }} -DCMAKE_C_STANDARD=${{ matrix.c-standard }} -DCMAKE_C_STANDARD_REQUIRED=TRUE -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }} -DCMAKE_CXX_STANDARD_REQUIRED=TRUE -DCMAKE_CXX_EXTENSIONS=${{ matrix.extensions }}
